{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "lang-expression",
    "version": "1.0.0-rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "rg354xlqgvbvnojdlh46smbnxa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-expressions",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.5.1-1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "5.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "5.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "5.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "lang-expression-1.0.0-rc1.jar",
          "url": "lang-expression-1.0.0-rc1.jar",
          "size": 64564,
          "sha512": "2493e8636f41136f2b278f85d69d80fe6674c713d5f05b386f8f94f31d2b48ed4b0d54bfb023aa4df872de283b61362aeb36ae74eb43c7a4881d5c9411d1c796",
          "sha256": "966542d98cd1adeb9fa9029f58a25c3e320ce25c337f6d263130ecda8d78250e",
          "sha1": "59c4fcf5cb79c279f250deb7d0da47060e60c869",
          "md5": "e569c22e31894db86d0a6856d4ba1e65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.lucene",
          "module": "lucene-expressions",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.5.1-1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "5.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "5.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "5.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "lang-expression-1.0.0-rc1.jar",
          "url": "lang-expression-1.0.0-rc1.jar",
          "size": 64564,
          "sha512": "2493e8636f41136f2b278f85d69d80fe6674c713d5f05b386f8f94f31d2b48ed4b0d54bfb023aa4df872de283b61362aeb36ae74eb43c7a4881d5c9411d1c796",
          "sha256": "966542d98cd1adeb9fa9029f58a25c3e320ce25c337f6d263130ecda8d78250e",
          "sha1": "59c4fcf5cb79c279f250deb7d0da47060e60c869",
          "md5": "e569c22e31894db86d0a6856d4ba1e65"
        }
      ]
    }
  ]
}
