{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-x-content",
    "version": "1.0.0-rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ok4rsytxdjh75ed55u3z7ny6ju"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch-core",
          "version": {
            "requires": "1.0.0-rc1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.26"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.11.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-smile",
          "version": {
            "requires": "2.11.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.11.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-cbor",
          "version": {
            "requires": "2.11.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-x-content-1.0.0-rc1.jar",
          "url": "opensearch-x-content-1.0.0-rc1.jar",
          "size": 140679,
          "sha512": "ed79d68f48b762dcb299f59185d4825b781910bddb76ff88c9d8c4fd870938045880a416b3c2aa9fe2d4bdfcf54e01ef6b828b9177ec0854a51ef8cc9fce9a70",
          "sha256": "65e477567b06dca2d6f7cd57b3c758d0ab38c6c12d3ed6e3a24a8cdf24ee7aa2",
          "sha1": "7c8dd0c5683c39785ca1c5176f47e099e26b61c6",
          "md5": "45f97a8134ea584380418e0cd4486899"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch-core",
          "version": {
            "requires": "1.0.0-rc1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.26"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.11.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-smile",
          "version": {
            "requires": "2.11.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.11.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-cbor",
          "version": {
            "requires": "2.11.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-x-content-1.0.0-rc1.jar",
          "url": "opensearch-x-content-1.0.0-rc1.jar",
          "size": 140679,
          "sha512": "ed79d68f48b762dcb299f59185d4825b781910bddb76ff88c9d8c4fd870938045880a416b3c2aa9fe2d4bdfcf54e01ef6b828b9177ec0854a51ef8cc9fce9a70",
          "sha256": "65e477567b06dca2d6f7cd57b3c758d0ab38c6c12d3ed6e3a24a8cdf24ee7aa2",
          "sha1": "7c8dd0c5683c39785ca1c5176f47e099e26b61c6",
          "md5": "45f97a8134ea584380418e0cd4486899"
        }
      ]
    }
  ]
}
