{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "lang-painless",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ntm6freatzc7nanvidi4n2i354"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.5.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.opensearch.plugin",
          "module": "opensearch-scripting-painless-spi",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lang-painless-1.0.0.jar",
          "url": "lang-painless-1.0.0.jar",
          "size": 703078,
          "sha512": "0bc2185c1def20d099d5510fabc1f00dc651f25b303a3c550c718dc29654f9db57fd5d3308e39d8e088d89f43dd3ab6be56c5780af9299b7ea2054117bfb6a96",
          "sha256": "66d622ac2ff8f3923abe3747cd655d06de121612351935cc7c91170895ab6bc7",
          "sha1": "f0e16bef6a61fa5cd0eccbb11e4812c664eb4b8f",
          "md5": "026425c3e573dfdb600517be0bcd3586"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.5.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.opensearch.plugin",
          "module": "opensearch-scripting-painless-spi",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "lang-painless-1.0.0.jar",
          "url": "lang-painless-1.0.0.jar",
          "size": 703078,
          "sha512": "0bc2185c1def20d099d5510fabc1f00dc651f25b303a3c550c718dc29654f9db57fd5d3308e39d8e088d89f43dd3ab6be56c5780af9299b7ea2054117bfb6a96",
          "sha256": "66d622ac2ff8f3923abe3747cd655d06de121612351935cc7c91170895ab6bc7",
          "sha1": "f0e16bef6a61fa5cd0eccbb11e4812c664eb4b8f",
          "md5": "026425c3e573dfdb600517be0bcd3586"
        }
      ]
    }
  ]
}
