{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-x-content",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "vgrf6p6kj5gazpuujouc57r6b4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.26"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.11.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-smile",
          "version": {
            "requires": "2.11.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.11.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-cbor",
          "version": {
            "requires": "2.11.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-x-content-1.0.0.jar",
          "url": "opensearch-x-content-1.0.0.jar",
          "size": 140679,
          "sha512": "04455de9ab449dc791cbd99c9e5952619cbb435f33bf178078ecdf3a2b0fa484c7a8a16480c0049c29390477a91f7b9469905c48091504348c097acc4cfc0b44",
          "sha256": "6a29940587ac334dd0e7d30c160b419b6a37ffad89e1a471e1e528c94c7fbffb",
          "sha1": "6bc1698b8895bedc93e3461f67268313f66e8c86",
          "md5": "43428b1dc7574f5a9eb469cdd5362105"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.26"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.11.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-smile",
          "version": {
            "requires": "2.11.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.11.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-cbor",
          "version": {
            "requires": "2.11.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-x-content-1.0.0.jar",
          "url": "opensearch-x-content-1.0.0.jar",
          "size": 140679,
          "sha512": "04455de9ab449dc791cbd99c9e5952619cbb435f33bf178078ecdf3a2b0fa484c7a8a16480c0049c29390477a91f7b9469905c48091504348c097acc4cfc0b44",
          "sha256": "6a29940587ac334dd0e7d30c160b419b6a37ffad89e1a471e1e528c94c7fbffb",
          "sha1": "6bc1698b8895bedc93e3461f67268313f66e8c86",
          "md5": "43428b1dc7574f5a9eb469cdd5362105"
        }
      ]
    }
  ]
}
