{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch",
    "version": "1.0.0-rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "6enunuq7xrfs7pjz2esde4jydq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch-core",
          "version": {
            "requires": "1.0.0-rc1"
          }
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-secure-sm",
          "version": {
            "requires": "1.0.0-rc1"
          }
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-x-content",
          "version": {
            "requires": "1.0.0-rc1"
          }
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-geo",
          "version": {
            "requires": "1.0.0-rc1"
          }
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-core",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-common",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-backward-codecs",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-grouping",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-highlighter",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-join",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-memory",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-misc",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-queries",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-queryparser",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-sandbox",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-spatial-extras",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-spatial3d",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-suggest",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-cli",
          "version": {
            "requires": "1.0.0-rc1"
          }
        },
        {
          "group": "com.carrotsearch",
          "module": "hppc",
          "version": {
            "requires": "0.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.tdunning",
          "module": "t-digest",
          "version": {
            "requires": "3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.hdrhistogram",
          "module": "HdrHistogram",
          "version": {
            "requires": "2.1.9"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.locationtech.spatial4j",
          "module": "spatial4j",
          "version": {
            "requires": "0.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.locationtech.jts",
          "module": "jts-core",
          "version": {
            "requires": "1.15.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.11.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.elasticsearch",
          "module": "jna",
          "version": {
            "requires": "5.5.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-1.0.0-rc1.jar",
          "url": "opensearch-1.0.0-rc1.jar",
          "size": 12906085,
          "sha512": "ee23f8b4cdc81fda574b96644ff77d4dec4450ec2a96bc28bc105f79ba24b985df97055198674176f15d1a4c3a209508f112528f36ec4910b996fc97548d1a5c",
          "sha256": "6d770b0aec48f18be1d805660cab9ca32a30aa4233b7939ad4c8eea603b82eee",
          "sha1": "9428142544743d67b9bb06799e8ccf50fe5d6b85",
          "md5": "08755c96dae2b3da15fb4738e63c8722"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch-core",
          "version": {
            "requires": "1.0.0-rc1"
          }
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-secure-sm",
          "version": {
            "requires": "1.0.0-rc1"
          }
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-x-content",
          "version": {
            "requires": "1.0.0-rc1"
          }
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-geo",
          "version": {
            "requires": "1.0.0-rc1"
          }
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-core",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-analyzers-common",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-backward-codecs",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-grouping",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-highlighter",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-join",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-memory",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-misc",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-queries",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-queryparser",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-sandbox",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-spatial-extras",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-spatial3d",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.lucene",
          "module": "lucene-suggest",
          "version": {
            "requires": "8.8.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.opensearch",
          "module": "opensearch-cli",
          "version": {
            "requires": "1.0.0-rc1"
          }
        },
        {
          "group": "com.carrotsearch",
          "module": "hppc",
          "version": {
            "requires": "0.8.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.tdunning",
          "module": "t-digest",
          "version": {
            "requires": "3.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.hdrhistogram",
          "module": "HdrHistogram",
          "version": {
            "requires": "2.1.9"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.locationtech.spatial4j",
          "module": "spatial4j",
          "version": {
            "requires": "0.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.locationtech.jts",
          "module": "jts-core",
          "version": {
            "requires": "1.15.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.11.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.11.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.elasticsearch",
          "module": "jna",
          "version": {
            "requires": "5.5.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-1.0.0-rc1.jar",
          "url": "opensearch-1.0.0-rc1.jar",
          "size": 12906085,
          "sha512": "ee23f8b4cdc81fda574b96644ff77d4dec4450ec2a96bc28bc105f79ba24b985df97055198674176f15d1a4c3a209508f112528f36ec4910b996fc97548d1a5c",
          "sha256": "6d770b0aec48f18be1d805660cab9ca32a30aa4233b7939ad4c8eea603b82eee",
          "sha1": "9428142544743d67b9bb06799e8ccf50fe5d6b85",
          "md5": "08755c96dae2b3da15fb4738e63c8722"
        }
      ]
    }
  ]
}
