{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch.plugin",
    "module": "lang-painless",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "yubdd3mzpbbnpifi3hnmetz7lm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.5.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.opensearch.plugin",
          "module": "opensearch-scripting-painless-spi",
          "version": {
            "requires": "1.0.0-beta1"
          }
        }
      ],
      "files": [
        {
          "name": "lang-painless-1.0.0-beta1.jar",
          "url": "lang-painless-1.0.0-beta1.jar",
          "size": 702887,
          "sha512": "ef607591d62a5c16d33fe7cd809e9884de22d42a2955da75740c30deea20d8ecd28fb270376befacf7fe2beb9b5e51de153e321df739c0dc2d786da43fe7843d",
          "sha256": "eee6afc59e002ca1775e9596f86bb113ef772ea78c490155cebe36315dfc3eb1",
          "sha1": "7678fe72500133c4a7358a06bf4cd750e2841a83",
          "md5": "cbee64f862c40900482844f6a9fcd69d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.5.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.opensearch.plugin",
          "module": "opensearch-scripting-painless-spi",
          "version": {
            "requires": "1.0.0-beta1"
          }
        }
      ],
      "files": [
        {
          "name": "lang-painless-1.0.0-beta1.jar",
          "url": "lang-painless-1.0.0-beta1.jar",
          "size": 702887,
          "sha512": "ef607591d62a5c16d33fe7cd809e9884de22d42a2955da75740c30deea20d8ecd28fb270376befacf7fe2beb9b5e51de153e321df739c0dc2d786da43fe7843d",
          "sha256": "eee6afc59e002ca1775e9596f86bb113ef772ea78c490155cebe36315dfc3eb1",
          "sha1": "7678fe72500133c4a7358a06bf4cd750e2841a83",
          "md5": "cbee64f862c40900482844f6a9fcd69d"
        }
      ]
    }
  ]
}
