{
  "formatVersion": "1.1",
  "component": {
    "group": "org.opensearch",
    "module": "opensearch-x-content",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "h7bvahrs5vccdaiqyfj7cjtzfe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch-core",
          "version": {
            "requires": "1.0.0-beta1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.26"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-smile",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-cbor",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-x-content-1.0.0-beta1.jar",
          "url": "opensearch-x-content-1.0.0-beta1.jar",
          "size": 140660,
          "sha512": "4aee9392a50896541ada2f19ac32778cd15490acadcb2d9b032a1b99bdfaa6c8743e59c8b4cad5f26fb419e32e337b6cebe871cb1a8ea9e1e79a3984e0bd35dc",
          "sha256": "668bf0083810644323187b785caa93218998bf4d8e14ea1bdfaf6da295cc3cb1",
          "sha1": "4b8e0d8923b00baa695fdd6a961c54c943de7174",
          "md5": "a7223abf34002ab70dcb38e94dc607ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.opensearch",
          "module": "opensearch-core",
          "version": {
            "requires": "1.0.0-beta1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.26"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-smile",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-cbor",
          "version": {
            "requires": "2.10.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "opensearch-x-content-1.0.0-beta1.jar",
          "url": "opensearch-x-content-1.0.0-beta1.jar",
          "size": 140660,
          "sha512": "4aee9392a50896541ada2f19ac32778cd15490acadcb2d9b032a1b99bdfaa6c8743e59c8b4cad5f26fb419e32e337b6cebe871cb1a8ea9e1e79a3984e0bd35dc",
          "sha256": "668bf0083810644323187b785caa93218998bf4d8e14ea1bdfaf6da295cc3cb1",
          "sha1": "4b8e0d8923b00baa695fdd6a961c54c943de7174",
          "md5": "a7223abf34002ab70dcb38e94dc607ef"
        }
      ]
    }
  ]
}
